POST http://localhost:8081/ap/api/registration
Content-Type: application/json

{
  "RegistrationRequest" : {
    "email": "v@v.h",
    "password": "aaaa",
    "firstName": "s",
    "lastName": "d",
    "birthDate": "12.02.1990"
  }

}